spring:
  application:
    name: minirestapi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

server:
  tomcat:
    threads:
      max: 200
      min-spare: 5
#  port: 8040

logging:
  level:
    org:
      springframework:
          security:
            oauth2: info



jwt:
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
  access-expiration-ms: 3600000
  refresh-expiration-ms: 604800000

app:
  upload-dir: uploads
