spring:
  application:
    name: springsecurity

  datasource:
    url: jdbc:mysql://localhost:3306/securityexam
    username: juns
    password: juns1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#  security:
#    user:
#      name: juns
#      password: iamwho1234

server:
  tomcat:
    threads:
      max: 200
      min-spare: 5


logging:
  level:
    org:
      springframework:
        security: trace