spring:
  application:
    name: springsecurity

  datasource:
    url: jdbc:mysql://localhost:3306/securityexam
    username: juns
    password: juns1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


#  security:
#    user:
#      name: juns
#      password: iamwho1234

server:
  tomcat:
    threads:
      max: 200
      min-spare: 5

logging:
  level:
    org:
      springframework:
        security: trace

jwt:
  secretKey: aPQbsKV7CZZDls/cnhW1EjqlGux45LAbBYpBhyk7nAk=
  refreshKey: 12346551456456446545644tyu23123156e1rt12r12
  access-expiration-ms: 1800000
  refresh-expiration-ms: 604800000